# Generated by Django 2.1.7 on 2019-10-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_submit', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(auto_now=True)),
                ('checkin_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('available', models.PositiveIntegerField(null=True)),
                ('quality', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('D', 'Damaged')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sport/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.ManyToManyField(to='sport.Sport')),
            ],
            options={
                'ordering': ('roll_no',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Sport'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='item_list',
            field=models.ManyToManyField(to='sport.ListOfItem'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Student'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkout_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sport.Checkout'),
        ),
    ]
