# Generated by Django 2.2.10 on 2020-06-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ('-date_of_issue', 'checkin_status')},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-updated_at', 'id')},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-updated_at', 'roll_no')},
        ),
        migrations.AddField(
            model_name='checkin',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='item_list',
            field=models.ManyToManyField(blank=True, to='sport.ListOfItem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=10),
        ),
    ]
